id = "rdf"
name = "RDF"
version = "0.1.0"
schema_version = 1
authors = ["Rene Pietzsch <rpietzsch@github.com>"]
description = "Syntax highlighting for RDF languages: SPARQL, Turtle, and TriG"
repository = "https://github.com/rpietzsch/zed-rdf-lsp"

[grammars.sparql]
repository = "https://github.com/GordianDziwis/tree-sitter-sparql"
rev = "d853661ca680d8ff7f8d800182d5782b61d0dd58"

[grammars.turtle]
repository = "https://github.com/GordianDziwis/tree-sitter-turtle"
rev = "7f789ea7ef765080f71a298fc96b7c957fa24422"
